version: '3.8'  

services:
  postgres:
    image: postgres:latest 
    container_name: my_postgres 
    environment:
      POSTGRES_USER: Adminchik  
      POSTGRES_PASSWORD: g7Tq1Xz  
      POSTGRES_DB: BookBase 
    ports:
      - "5432:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:  